# Generated by Django 5.1 on 2024-08-24 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculoAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroModeloModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=75)),
                ('nome', models.CharField(max_length=75)),
                ('codigoMarca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='veiculoAPP.marcamodel')),
            ],
        ),
    ]
