# Generated by Django 5.1 on 2024-08-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculoAPP', '0002_carromodelomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carromodelomodel',
            name='codigoMarca',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
