# Generated by Django 5.1 on 2024-08-24 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculoAPP', '0003_alter_carromodelomodel_codigomarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carromodelomodel',
            name='codigoMarca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='veiculoAPP.marcamodel'),
        ),
    ]
